### ISSUE TITLE
Highlighting color doesn't change

### ISSUE THREAD

**Issue by blasco** [neoclide/coc-yank#12] opened 2019-10-21 11:25 UTC
I've updated the color as suggested:

```
hi HighlightedyankRegion gui=NONE guibg=#13354A term=NONE ctermbg=0
```

But this doesn't take any effect

**Comment by chemzqm** [comment] 2019-10-21 11:28
I can't reproduce.

**Comment by chemzqm** [comment] 2019-10-21 11:31
Closing unless you can provide minimal vimrc to reproduce.
You can try that command in your vim's command line.

**Closed as completed by chemzqm** 2019-10-21 11:31 UTC
Labels: question

**Comment by blasco** [comment] 2019-10-21 12:02
It doesn't work. This fixes the issue:
```
autocmd VimEnter * execute "hi HighlightedyankRegion gui=NONE guibg=White term=NONE ctermbg=0"
```

**Comment by chemzqm** [comment] 2019-10-21 12:20
It's because your colorsheme overwrite your custom highlight.
