### ISSUE TITLE
<C-j> works but <C-k> doesn't when navigating the yank list

### ISSUE THREAD

**Issue by blasco** [neoclide/coc-yank#11] opened 2019-10-21 11:24 UTC
I can navigate down with `<c-j>` but I cannot go up with `<c-k>`. This works in other coc-lists, it only happens in coc-yank that I trigger with `<space>y` as suggested.

**Comment by chemzqm** [comment] 2019-10-21 11:28
I can't reproduce.

**Comment by chemzqm** [comment] 2019-10-21 11:29
Closing unless you can provide minimal vimrc to reproduce

**Closed as completed by chemzqm** 2019-10-21 11:29 UTC
Labels: question

**Comment by chemzqm** [comment] 2019-10-21 11:35
The suggested command start CocList on normal mode, use normal command to navigate.

**Comment by blasco** [comment] 2019-10-21 11:50
You are right, that was the issue.
